// ─── Auth Types ───────────────────────────────────────────────────────────────

export interface User {
  id: string;
  email: string;
  full_name?: string;
  role: 'admin' | 'field_user' | 'partner';
  avatar_url?: string;
  created_at: string; 
  credits: number;
}

// ─── Tree Record Types ─────────────────────────────────────────────────────────

export type HealthStatus = 'healthy' | 'sick' | 'dead' | 'unknown';
export type TreeCondition = 'Healthy' | 'Stressed' | 'Diseased' | 'Dead';
export type MultiStemOption = 'Yes' | 'No';
export type LandType = 'Roadside' | 'Park' | 'Residential' | 'Institutional' | 'Forest' | 'Other';

export interface TreeRecord {
  id: string;
  tree_id?: string;
  user_id: string;
  project_id?: string;
  photo_url: string;
  photo_urls?: string[] | null;
  latitude: number;
  longitude: number;
  species?: string;
  scientific_name?: string;
  health_status: HealthStatus;
  notes?: string;
  submitted_at: string;
  synced: boolean;
  event_type?: EventType;
  quantity?: number;
  dbh_cm?: number;
  height_m?: number;
  wood_density?: number;
  crown_diameter_m?: number;
  tree_condition?: TreeCondition;
  multi_stem?: MultiStemOption;
  age_years?: number;
  land_type?: LandType;
  surveyor?: string;
  survey_date?: string;
  locked: boolean;
  // Joined fields
  submitted_by?: string;
  project_name?: string;
}

export interface TreeRecordInsert {
  id?: string;
  user_id: string;
  tree_id?: string;
  project_id?: string;
  photo_url: string;
  photo_urls?: string[] | null;
  latitude: number;
  longitude: number;
  species?: string;
  scientific_name?: string;
  health_status: HealthStatus;
  notes?: string;
  synced?: boolean;
  event_type?: EventType;
  quantity?: number;
  dbh_cm?: number;
  height_m?: number;
  wood_density?: number;
  crown_diameter_m?: number;
  tree_condition?: TreeCondition;
  multi_stem?: MultiStemOption;
  age_years?: number;
  land_type?: LandType;
  surveyor?: string;
  survey_date?: string;
  locked?: boolean;
}

// ─── Location Types ────────────────────────────────────────────────────────────

export interface Coordinates {
  latitude: number;
  longitude: number;
  accuracy?: number;
}

// ─── Project Types ─────────────────────────────────────────────────────────────

export interface Project {
  id: string;
  name: string;
  description?: string;
  status: string;
}

// ─── Task Types ────────────────────────────────────────────────────────────────

export type TaskStatus = 'assigned' | 'in_progress' | 'completed' | 'approved' | 'rejected';

export interface Task {
  id: string;
  task_code?: string | null;   // TRK-XXXX-T001 format — generated by DB
  name: string;
  project_id?: string;
  assignee_id: string;
  target_count: number;
  location?: string;
  priority: 'high' | 'medium' | 'low';
  due_date?: string | null;
  started_at?: string | null;
  completed_at?: string | null;
  created_at: string;
  // Derived live from actual tree captures (never stored — fully automatic)
  captured: number;
  remaining: number;
  progress: number; // 0..100
  status: TaskStatus;
  // Review fields
  reviewed_by?: string | null;
  review_notes?: string | null;
  reviewed_at?: string | null;
  tree_id?: string | null;     // linked tree record
  created_by?: string | null;  // auth_id of the Admin/Partner who assigned this task
  // Joined fields
  project_name?: string;
  assigned_by_name?: string;   // display name resolved client-side from created_by
  notes?: string;
  // Tree capture fields (for completed tasks from tree captures)
  photo_url?: string;
  latitude?: number;
  longitude?: number;
  tree_condition?: string;
  tree_condition_color?: string;
  surveyor?: string;
  // Audit follow-ups of a tree that is already counted. These are not new trees.
  task_type?: string | null;
  audit_round?: number | null;
  tree_record_id?: string | null;
  title?: string;
}

// ─── Task Store Types ──────────────────────────────────────────────────────────

export interface TaskState {
  tasks: Task[];
  localTasks: Task[]; // tasks created in the UI, stored on-device (no DB needed)
  setTasks: (tasks: Task[]) => void;
  setLocalTasks: (localTasks: Task[]) => void;
  // The task "Start Now" was tapped from, if any — carried across the whole
  // Capture flow (Camera → MapPicker → TreeForm) so the exact right task gets
  // completed on submit, without threading a param through every screen.
  activeTaskId: string | null;
  setActiveTaskId: (taskId: string | null) => void;
}

// ─── Navigation Types ──────────────────────────────────────────────────────────

export type RootStackParamList = {
  Login: undefined;
  Main: undefined;
};

export type CaptureStackParamList = {
  CaptureCamera: undefined;
  MapPicker: { photoUris: string[]; initialCoords?: Coordinates };
  TreeForm: { photoUris: string[]; coords: Coordinates };
  SubmitSuccess: { treeId: string };
};

export type HistoryStackParamList = {
  HistoryList: undefined;
  TreeDetail: { treeId: string; taskId?: string | null; rejectionNotes?: string | null; asAuditProfile?: boolean };
};

// ─── Store Types ───────────────────────────────────────────────────────────────

export interface AuthState {
  user: User | null;
  session: any | null;
  assignedProjects: Project[];
  activeProjectId: string | null;
  // True while the user is choosing their projects on the login page
  projectSelectionPending: boolean;
  setUser: (user: User | null) => void;
  setSession: (session: any | null) => void;
  setAssignedProjects: (projects: Project[]) => void;
  setActiveProjectId: (projectId: string | null) => void;
  setProjectSelectionPending: (pending: boolean) => void;
  setUserCredits: (credits: number) => void;
  refreshCredits: () => Promise<void>;
  signOut: () => Promise<void>;
}

// ─── User Project Assignment Types ─────────────────────────────────────────────

export interface TreeState {
  trees: TreeRecord[];
  setTrees: (trees: TreeRecord[]) => void;
  addTree: (tree: TreeRecord) => void;
  updateTree: (id: string, updates: Partial<TreeRecord>) => void;
  removeTree: (id: string) => void;
}

// ─── API Response Types ────────────────────────────────────────────────────────

export interface ApiResponse<T> {
  data: T | null;
  error: string | null;
}

// ─── Form Types ────────────────────────────────────────────────────────────────

export type EventType = 'Planting' | 'Installation' | 'Restoration' | 'Measurement' | 'Survey' | 'Other';

export const EVENT_TYPES: EventType[] = [
  'Planting',
  'Installation',
  'Restoration',
  'Measurement',
  'Survey',
  'Other',
];

export interface TreeFormData {
  species?: string;
  scientific_name: string;
  health_status: HealthStatus;
  notes: string;
  project_id: string;
  event_type: EventType;
  quantity: number;
  tree_id: string;
  dbh_cm: string;
  height_m: string;
  wood_density: string;
  crown_diameter_m: string;
  tree_condition: TreeCondition;
  multi_stem: MultiStemOption;
  age_years: string;
  land_type: LandType;
  surveyor: string;
  survey_date: string;
}

export interface SpeciesDefault {
  common: string;
  scientific: string;
  value: number;
}

/** Common name, scientific name, and default number from the species defaults sheet. */
export const SPECIES_DEFAULTS: SpeciesDefault[] = [
  { common: 'Neem', scientific: 'Azadirachta indica', value: 15 },
  { common: 'Mango', scientific: 'Mangifera indica', value: 15 },
  { common: 'Teak', scientific: 'Tectona grandis', value: 7 },
  { common: 'Eucalyptus', scientific: 'Eucalyptus spp.', value: 30 },
  { common: 'Banyan', scientific: 'Ficus benghalensis', value: 100 },
  { common: 'Peepal', scientific: 'Ficus religiosa', value: 50 },
  { common: 'Ashoka', scientific: 'Saraca asoca', value: 12 },
  { common: 'Gulmohar', scientific: 'Delonix regia', value: 15 },
  { common: 'Indian Rosewood', scientific: 'Dalbergia sissoo', value: 18 },
  { common: 'Cashew', scientific: 'Anacardium occidentale', value: 12 },
  { common: 'Tamarind', scientific: 'Tamarindus indica', value: 15 },
  { common: 'Jamun', scientific: 'Syzygium cumini', value: 15 },
  { common: 'Pongamia', scientific: 'Pongamia pinnata', value: 12 },
  { common: 'Babul / Acacia', scientific: 'Acacia nilotica', value: 15 },
  { common: 'Prosopis', scientific: 'Prosopis juliflora', value: 18 },
  { common: 'Rain Tree', scientific: 'Albizia saman', value: 25 },
  { common: 'Ash', scientific: 'Fraxinus spp.', value: 18 },
  { common: 'Oak', scientific: 'Quercus spp.', value: 25 },
  { common: 'Maple', scientific: 'Acer spp.', value: 20 },
  { common: 'Pine', scientific: 'Pinus spp.', value: 18 },
  { common: 'Spruce', scientific: 'Picea spp.', value: 25 },
  { common: 'Douglas fir', scientific: 'Pseudotsuga menziesii', value: 30 },
  { common: 'Mahogany', scientific: 'Swietenia macrophylla', value: 20 },
  { common: 'Bamboo (stand)', scientific: 'Bambusoideae', value: 25 },
  { common: 'Mangrove (average)', scientific: 'Rhizophora spp.', value: 10 },
];

export const TREE_SPECIES = SPECIES_DEFAULTS.map((item) => item.common);

export function getSpeciesDefault(commonName?: string | null): SpeciesDefault | undefined {
  const key = commonName?.trim().toLowerCase();
  if (!key) return undefined;
  return SPECIES_DEFAULTS.find((item) => item.common.toLowerCase() === key);
}

export const HEALTH_STATUS_OPTIONS: { label: string; value: HealthStatus; color: string }[] = [
  { label: 'Healthy', value: 'healthy', color: '#22c55e' },
  { label: 'Sick', value: 'sick', color: '#f59e0b' },
  { label: 'Dead', value: 'dead', color: '#ef4444' },
  { label: 'Unknown', value: 'unknown', color: '#6b7280' },
];

export const TREE_CONDITION_OPTIONS: { label: TreeCondition; color: string }[] = [
  { label: 'Healthy', color: '#22c55e' },
  { label: 'Stressed', color: '#f59e0b' },
  { label: 'Diseased', color: '#ef4444' },
  { label: 'Dead', color: '#6b7280' },
];

export const LAND_TYPE_OPTIONS: LandType[] = [
  'Roadside',
  'Park',
  'Residential',
  'Institutional',
  'Forest',
  'Other',
];

export interface MonitoringRound {
  round: number;
  label: string;
  subtitle: string;
  color: string;
  icon: string;
}

/** TESTING: four sequential field audits, one every 30 minutes. */
export const MONITORING_ROUNDS: MonitoringRound[] = [
  { round: 1, label: 'Audit 1', subtitle: 'Survival check · 30 min', color: '#16a34a', icon: 'leaf' },
  { round: 2, label: 'Audit 2', subtitle: 'Growth check · 60 min', color: '#0ea5e9', icon: 'trending-up' },
  { round: 3, label: 'Audit 3', subtitle: 'Health check · 90 min', color: '#d97706', icon: 'pulse' },
  { round: 4, label: 'Audit 4', subtitle: 'Final check · 120 min', color: '#7c3aed', icon: 'checkmark-done' },
];

export function getMonitoringRoundInfo(round: number | null | undefined): MonitoringRound {
  return MONITORING_ROUNDS.find((item) => item.round === Number(round)) ?? MONITORING_ROUNDS[0];
}

// ─── Geofence Types ──────────────────────────────────────────────────────────

export interface GeofenceZone {
  id: string;
  treeId: string;
  latitude: number;
  longitude: number;
  radius: number; // meters
  label?: string;
}

export type GeofenceEvent = 'enter' | 'exit';

export interface GeofenceAlert {
  zone: GeofenceZone;
  event: GeofenceEvent;
  timestamp: number;
}

// ─── Map Screen Navigation ──────────────────────────────────────────────────

export type MainTabParamList = {
  Home: undefined;
  Capture: undefined;
  Map: { focusTreeId?: string } | undefined;
  Task: undefined;
  History: undefined;
  Profile: undefined;
};
